// VueJS/components/Forms/Contact.vue
<template>
  <div class="page-wrap">
    <hidden point="mdDown">
      <div class="bg-deco" />
    </hidden>
    <div class="parallax">
      <cross-parallax />
    </div>
    <v-snackbar
      :timeout="4000"
      top
      right
      v-model="snackbar"
      class="notification"
    >
      <div class="action">
        Message Sent
      </div>
      <v-btn
        text
        icon
        @click="snackbar = false"
      >
        <v-icon>mdi-close</v-icon>
      </v-btn>
    </v-snackbar>
    <hidden point="mdUp">
      <div class="logo logo-header">
        <nuxt-link :to="routeLink.architect.home">
          <img :src="logo" alt="logo">
          <span class="use-text-title">
            {{ brand.architect.projectName }}
          </span>
        </nuxt-link>
      </div>
    </hidden>
    <v-container class="max-lg inner-wrap">
      <v-btn
        :href="routeLink.architect.home"
        icon
        class="backtohome"
      >
        <i class="ion-ios-home-outline" />
        <i class="ion-ios-arrow-round-back-outline" />
      </v-btn>
      <v-row>
        <v-col lg="1" cols="12" class="hidden-xs-only">&nbsp;</v-col>
        <v-col lg="5" cols="12" class="wrap-deco">
          <hidden point="mdDown">
            <div class="frm-deco" />
          </hidden>
          <v-card class="form-box fragment-fadeUp">
            <div class="full-form-wrap">
              <div class="form">
                <title-main
                  :desc="$t('common.contact_subtitle')"
                  head="Contact Us"
                />
                <v-form
                  ref="form"
                  v-model="valid"
                >
                  <v-row class="spacing6">
                    <v-col cols="12" sm="12" class="px-6">
                      <v-text-field
                        v-model="name"
                        :rules="nameRules"
                        :label="$t('common.form_name')"
                        required
                      />
                    </v-col>
                    <v-col cols="12" sm="12" class="px-6">
                      <v-text-field
                        v-model="email"
                        :rules="emailRules"
                        :label="$t('common.form_email')"
                        required
                      />
                    </v-col>
                    <v-col cols="12" sm="12" class="px-6">
                      <v-text-field
                        v-model="phone"
                        :label="$t('common.form_phone')"
                      />
                    </v-col>
                    <v-col cols="12" class="px-6">
                      <v-textarea
                        v-model="message"
                        rows="6"
                        :label="$t('common.form_message')"
                      />
                    </v-col>
                  </v-row>
                  <div class="form-control-label">
                    <v-checkbox
                      v-model="checkbox"
                      color="secondary"
                      :rules="[v => !!v || 'You must agree to continue!']"
                      :label="$t('common.form_terms')"
                      required
                    />
                    <span>
                      <a href="#" class="link">
                        {{ $t('common.form_privacy') }}
                      </a>
                    </span>
                  </div>
                  <div class="btn-area">
                    <v-btn
                      :block="isMobile"
                      large
                      color="primary"
                      @click="validate"
                    >
                      {{ $t('common.form_send') }}
                      <v-icon class="right-icon">mdi-send</v-icon>
                    </v-btn>
                  </div>
                </v-form>
              </div>
            </div>
          </v-card>
        </v-col>
        <v-col lg="6" cols="12">
          <hidden point="mdDown">
            <v-card class="map" raised>
              <GMap
                ref="gMap"
                :center="{lat: locations[0].lat, lng: locations[0].lng}"
                :options="{fullscreenControl: false}"
                :zoom="6"
              >
                <GMapMarker
                  ref="gMarker"
                  v-for="location in locations"
                  :key="location.id"
                  :position="{lat: location.lat, lng: location.lng}"
                >
                  <GMapInfoWindow>
                    <div class="bubel">
                      <h6 class="title pb-2 px-3">
                        Head Quarter
                      </h6>
                      <v-row class="ma-3">
                        <v-col item sm="6" cols="12" class="pa-0">
                          <p>
                            <v-icon class="icon">mdi-phone</v-icon>
                            +98 765 432 10
                          </p>
                        </v-col>
                        <v-col item sm="6" cols="12" class="pa-0">
                          <p>
                            <v-icon class="icon">mdi-email</v-icon>
                            hello@luxi.com
                          </p>
                        </v-col>
                        <v-col item sm="12" cols="12" class="pa-0">
                          <p>
                            <v-icon class="icon">mdi-map-marker</v-icon>
                            Lorem ipsum street Block C - Vestibullum Building
                          </p>
                        </v-col>
                      </v-row>
                    </div>
                  </GMapInfoWindow>
                </GMapMarker>
              </GMap>
            </v-card>
          </hidden>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style lang="scss" scoped>
@import './form-style.scss';
</style>

<script>
import logo from '~/static/images/architect-logo.svg'
import brand from '~/static/text/brand'
import routeLink from '~/static/text/link'
import Title from '../Title'
import CrossParallax from '../Parallax/Cross'
import Hidden from '../Hidden'

export default {
  components: {
    'title-main': Title,
    CrossParallax,
    Hidden
  },
  data: () => ({
    currentLocation: {},
    locations: [
      {
        lat: 44.933076,
        lng: 15.629058
      }
    ],
    logo: logo,
    brand: brand,
    routeLink: routeLink,
    valid: true,
    snackbar: false,
    name: '',
    nameRules: [v => !!v || 'Name is required'],
    email: '',
    emailRules: [
      v => !!v || 'E-mail is required',
      v => /.+@.+\..+/.test(v) || 'E-mail must be valid'
    ],
    phone: '',
    company: '',
    message: '',
    checkbox: false
  }),
  methods: {
    validate() {
      if (this.$refs.form.validate()) {
        this.snackbar = true
      }
    }
  },
  computed: {
    isMobile() {
      const smDown = this.$store.state.breakpoints.smDown
      return smDown.indexOf(this.$mq) > -1
    }
  }
}
</script>

// ReactJS/components/Forms/Contact.js
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import clsx from 'clsx';
import Button from '@material-ui/core/Button';
import Hidden from '@material-ui/core/Hidden';
import useMediaQuery from '@material-ui/core/useMediaQuery';
import { useTheme } from '@material-ui/core/styles';
import IconButton from '@material-ui/core/IconButton';
import FormControlLabel from '@material-ui/core/FormControlLabel';
import Paper from '@material-ui/core/Paper';
import Container from '@material-ui/core/Container';
import Grid from '@material-ui/core/Grid';
import SendIcon from '@material-ui/icons/Send';
import EmailIcon from '@material-ui/icons/Email';
import PhoneIcon from '@material-ui/icons/LocalPhone';
import LocationIcon from '@material-ui/icons/LocationOn';
import Typography from '@material-ui/core/Typography';
import Snackbar from '@material-ui/core/Snackbar';
import { ValidatorForm, TextValidator } from 'react-material-ui-form-validator';
import {
  Map,
  Marker,
  GoogleApiWrapper,
  InfoWindow
} from 'google-maps-react18';
import { useTranslation } from 'next-i18next';
import { useText } from '~/theme/common';
import brand from '~/public/text/brand';
import logo from '~/public/images/architect-logo.svg';
import routeLink from '~/public/text/link';
import useStyles from './form-style';
import CrossParallax from '../Parallax/Cross';
import Checkbox from './Checkbox';
import Title from '../Title';

function BubleMark() {
  const classes = useStyles();
  return (
    <div className={classes.bubelWrap}>
      <div className={classes.buble}>
        <Typography variant="h6" gutterBottom>
          Head Quarter
        </Typography>
        <Grid container>
          <Grid item sm={6} xs={12}>
            <Typography>
              <PhoneIcon className={classes.icon} />
              +98 765 432 10
            </Typography>
          </Grid>
          <Grid item sm={6} xs={12}>
            <Typography>
              <EmailIcon className={classes.icon} />
              hello@luxi.com
            </Typography>
          </Grid>
          <Grid item xs={12}>
            <Typography>
              <LocationIcon className={classes.icon} />
              Lorem ipsum street Block C - Vestibullum Building
            </Typography>
          </Grid>
        </Grid>
      </div>
    </div>
  );
}

function MapContainer(props) {
  const [activeMarker, setActive] = useState({});
  const [showingInfoWindow, setShow] = useState(false);
  const { google } = props;
  // eslint-disable-next-line
  const onMarkerClick = (props, marker) => {
    setActive(marker);
    setShow(true);
  };

  const onMapClicked = () => {
    if (showingInfoWindow) {
      setShow(false);
      setActive(null);
    }
  };

  return (
    <Map
      google={google}
      onClick={onMapClicked}
      style={{ width: '100%', height: '700px', position: 'relative' }}
      initialCenter={{
        lat: 37.759703,
        lng: -122.428093
      }}
      zoom={14}
    >
      <Marker
        onClick={onMarkerClick}
        position={{ lat: 37.759703, lng: -122.428093 }}
      />
      <InfoWindow
        marker={activeMarker}
        visible={showingInfoWindow}
      >
        <div>
          <BubleMark />
        </div>
      </InfoWindow>
    </Map>
  );
}

MapContainer.propTypes = {
  google: PropTypes.object.isRequired
};

const MapWithAMarker = GoogleApiWrapper({ apiKey: null })(MapContainer);

function Contact() {
  const classes = useStyles();
  const text = useText();
  const { t } = useTranslation('common');
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
  const [values, setValues] = useState({
    name: '',
    email: '',
    phone: '',
    company: '',
    message: ''
  });

  useEffect(() => {
    ValidatorForm.addValidationRule('isTruthy', value => value);
  });

  const [openNotif, setNotif] = useState(false);

  const [check, setCheck] = useState(false);

  const handleChange = name => event => {
    setValues({ ...values, [name]: event.target.value });
  };

  const handleCheck = event => {
    setCheck(event.target.checked);
  };

  const handleSubmit = () => {
    setNotif(true);
  };

  const handleClose = () => {
    setNotif(false);
  };

  return (
    <div className={classes.pageWrap}>
      <Hidden mdDown>
        <div className={classes.bgDeco} />
      </Hidden>
      <div className={classes.parallax}>
        <CrossParallax />
      </div>
      <Snackbar
        anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        key="top right"
        open={openNotif}
        autoHideDuration={4000}
        onClose={handleClose}
        ContentProps={{
          'aria-describedby': 'message-id',
        }}
        message={<span id="message-id">Message Sent</span>}
      />
      <Hidden mdUp>
        <div className={clsx(classes.logo, classes.logoHeader)}>
          <a href={routeLink.architect.home}>
            <img src={logo} alt="logo" />
            <Typography component="span">
              {brand.architect.projectName}
            </Typography>
          </a>
        </div>
      </Hidden>
      <Container maxWidth="lg" className={classes.innerWrap}>
        <IconButton href={routeLink.architect.home} className={classes.backtohome}>
          <i className="ion-ios-home-outline" />
          <i className="ion-ios-arrow-round-back" />
        </IconButton>
        <Grid container>
          <Grid item lg={1} xs={12} />
          <Grid item lg={5} xs={12} className={classes.wrapDeco}>
            <Hidden mdDown>
              <div className={classes.frmDeco} />
            </Hidden>
            <Paper className={clsx(classes.formBox, 'fragment-fadeUp')}>
              <div className={classes.fullFromWrap}>
                <div className={classes.form}>
                  <Title
                    head="Contact Us"
                    desc={t('contact_subtitle')}
                  />
                  <ValidatorForm
                    onSubmit={handleSubmit}
                    onError={errors => console.log(errors)}
                  >
                    <Grid container spacing={6}>
                      <Grid item xs={12}>
                        <TextValidator
                          className={classes.input}
                          label={t('form_name')}
                          onChange={handleChange('name')}
                          name="Name"
                          value={values.name}
                          validators={['required']}
                          errorMessages={['This field is required']}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextValidator
                          className={classes.input}
                          label={t('form_email')}
                          onChange={handleChange('email')}
                          name="Email"
                          value={values.email}
                          validators={['required', 'isEmail']}
                          errorMessages={['This field is required', 'email is not valid']}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextValidator
                          className={classes.input}
                          label={t('form_phone')}
                          onChange={handleChange('phone')}
                          name="Phone"
                          value={values.phone}
                        />
                      </Grid>
                      <Grid item xs={12}>
                        <TextValidator
                          multiline
                          rows="6"
                          className={classes.input}
                          label={t('form_message')}
                          onChange={handleChange('message')}
                          name="Message"
                          value={values.message}
                        />
                      </Grid>
                    </Grid>
                    <FormControlLabel
                      className={classes.checkArea}
                      control={(
                        <Checkbox
                          validators={['isTruthy']}
                          errorMessages="This field is required"
                          checked={check}
                          value={check}
                          onChange={(e) => handleCheck(e)}
                          color="primary"
                        />
                      )}
                      label={(
                        <span className={text.paragraph}>
                          {t('form_terms')}
                          <br />
                          <a href="#">
                            {t('form_privacy')}
                          </a>
                        </span>
                      )}
                    />
                    <div className={classes.btnArea}>
                      <Button variant="contained" fullWidth={isMobile} type="submit" color="primary" size="large">
                        {t('form_send')}
                        <SendIcon className={classes.rightIcon} />
                      </Button>
                    </div>
                  </ValidatorForm>
                </div>
              </div>
            </Paper>
          </Grid>
          <Grid item lg={6} xs={12}>
            <Hidden mdDown>
              <Paper className={classes.map} elevation={10}>
                <MapWithAMarker
                  googleMapURL="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing,places"
                  loadingElement={<div style={{ height: '100%' }} />}
                  containerElement={<div style={{ height: '700px' }} />}
                  mapElement={<div style={{ height: '100%' }} />}
                />
              </Paper>
            </Hidden>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
}

export default Contact;
